name: Release Pull Request

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Release Type(next, beta, alpha, latest)"
        required: true
        default: "latest"
        options:
          - canary
          - alpha
          - beta
          - latest

jobs:
  release:
    name: Create Release Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 1
      - name: Create Release Pull Request
        uses: web-infra-dev/actions@v2
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          version: ${{ github.event.inputs.version }}
          versionNumber: "auto"
          type: "pull request"
          tools: "changeset"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
